### ISSUE TITLE
Values of time constants messed up?

### ISSUE THREAD

**Issue by albmar** [rockyjvec/EasyAPI#1]
I think these values [from line 95 to 101](https://github.com/rockyjvec/EasyAPI/blob/master/EasyAPI.cs#L95-L101) aren't correct:

``` C#
    /*** Constants ***/   
    public const long Nanoseconds = 100;  
    public const long Milliseconds = 10000;  
    public const long Seconds = 10000000;   
    public const long Minutes = 600000000;   
    public const long Hours = 36000000000;   
    public const long Days = 864000000000; 
```

Assuming that all these values have the same unit (10 ps?) and the constants mean what their name is telling us, then these values aren't correct.

`EasyAPI.Nanoseconds * 10 ps = 1,000 ps = 1 ns`, but
`EasyAPI.Milliseconds * 10 ps = 100,000 ps = 100 ns != 1ms` and
`EasyAPI.Seconds * 10 ps = 100,000,000 ps = 100 μs != 1s` etc.

For readability and maintainability I would recommend to write it like this:

``` C#
    /*** Constants ***/   
    public const long Nanoseconds = 100;  
    public const long Milliseconds = 1000 * 1000 * Nanoseconds;  
    public const long Seconds = 1000 * Milliseconds;   
    public const long Minutes = 60 * Seconds;   
    public const long Hours = 60 * Minutes;   
    public const long Days = 24 * Hours; 
```

**Note:** You are also missing the SI-prefix _micro_ which is between _milli_ and _nano_. http://en.wikipedia.org/wiki/Metric_prefix

**Comment by rockyjvec** [comment]
Thanks for catching that!  You are right, The Nanoseconds value is wrong.   Those values are supposed to be in ticks as specified here: https://msdn.microsoft.com/en-us/library/system.datetime.ticks%28v=vs.110%29.aspx
I messed up the Nanoseconds because I put 100 ticks = a nanosecond instead of a tick = 100 nanosecnds.   Good idea to write them like that and add micro.
